# Generated by Django 5.2 on 2025-04-27 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReciepesApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='directions',
            field=models.TextField(),
        ),
    ]
