# Generated by Django 5.2 on 2025-05-10 08:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReciepesApp', '0003_alter_recipes_image_boards_saved_recipes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boards',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='saved_recipes',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='saved_recipes',
            unique_together={('user', 'recipe', 'board')},
        ),
    ]
