# Generated by Django 5.2 on 2025-05-11 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ReciepesApp', '0003_alter_recipes_image'),
        ('ReciepesApp', '0004_alter_boards_user_alter_saved_recipes_user_and_more'),
    ]

    operations = [
    ]
