# Generated by Django 5.1.2 on 2025-06-01 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReciepesApp', '0005_merge_20250511_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saved_recipes',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_recipes', to='ReciepesApp.recipes'),
        ),
    ]
