# Generated by Django 5.2 on 2026-06-21 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReciepesApp', '0006_alter_saved_recipes_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='image_name',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
    ]
