# Generated by Django 5.2 on 2026-06-21 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReciepesApp', '0006_alter_saved_recipes_recipe'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boards',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='recipes',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'ordering': ['-user_created_at']},
        ),
        migrations.AlterField(
            model_name='recipes',
            name='image_name',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('user', 'user')], default='user', max_length=30),
        ),
        migrations.DeleteModel(
            name='Passwords',
        ),
    ]
