# Generated by Django 5.2 on 2026-06-21 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ReciepesApp', '0007_alter_boards_options_alter_recipes_options_and_more'),
        ('ReciepesApp', '0007_alter_recipes_image_name'),
    ]

    operations = [
    ]
